"""empty message

Revision ID: 72455507a732
Revises: 90c86e441e67
Create Date: 2026-02-08 19:17:23.562484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72455507a732'
down_revision = '90c86e441e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('genre')
        batch_op.drop_column('cover_url')
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###
