"""add named FK to start_page

Revision ID: 90c86e441e67
Revises: c0b2f6d067bf
Create Date: 2026-02-06 10:45:46.982699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c86e441e67'
down_revision = 'c0b2f6d067bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_story_start_page', 'pages', ['start_page_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_story_start_page', type_='foreignkey')

    # ### end Alembic commands ###
