# Generated by Django 6.0.2 on 2026-02-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="ending_page_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="play",
            name="story_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
