# Generated by Django 6.0.2 on 2026-02-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0002_alter_play_ending_page_id_alter_play_story_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
